config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", passwords: 'passwords', masquerades: 'admin/masquerades' }

  get '/result', to: 'static#s3_results', as: :s3_results

  resources :signed_urls, only: :index

  namespace :admin do
    root to: 'home#index'

    resources :users
    resources :seo_meta
  end

  resources :days do
    member do
      get :add_moments
    end
    resources :moments
  end

  get "/404", to: "errors#routing"
  post "/404", to: "errors#routing"
  put "/404", to: "errors#routing"
  patch "/404", to: "errors#routing"
  delete "/404", to: "errors#routing"
end

app/views/shared/404.html.haml
%h3= 'errors.not_found.title'.t

%p= 'errors.not_found.content'.t

app/views/shared/_carousel.html.haml
.slider.slider-header{data: options}
  - if options[:loader]
    .slider-loader
      .icon-wrapper
        = icon 'circle-o-notch', class: 'fa-spin'

  .slider-next
  .slider-previous
  .slider-wrapper
    .slider-items
      - items.each_with_index do |item,index|
        .slider-item{data: {index: index}}
          .visual{style: "background-color: #{item.try(:bg_color)}; background-image: url(#{item.carousel})"}
            - if item.respond_to?(:title)
              .content.hidden-xs
                %h3{style: "color: #{item.try(:title_color)};"}!= item.title
                %div{style: "color: #{item.try(:body_color)};"}!= item.try(:body)

app/views/shared/_flash.html.haml
- flash_type_map = { notice: 'success', alert: 'danger', error: 'danger' }

- if flash.present? && flash.any?
  .container-fluid
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        .alert.alert-dismissable{ class: "alert-#{flash_type_map[name.intern] || name}" }
          %button.close{ type: :button, data: { dismiss: 'alert' } }= icon(:times)
          != msg

app/views/shared/_logo.html.haml
.logo
  .sky
  .sun
  .city
  .car
  .crown

app/views/shared/_markdown_help.html.haml
.markdown-help
  %button.btn.btn-default
    = icon :times

  .wrapper
    %h2 Aide Markdown

    %h3 Styles de texte

    .row.section
      - content = capture_haml do
        :plain
          _Italique_
          *Italique*
          __Gras__
          **Gras**
          ~~Raturé~~
          [Lien](http://www.google.fr/)
          > Citation

      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

    %h3 Alignements

    .row.section
      - content = capture_haml do
        :plain
          -->>
          Texte à droite
          -->>

          <<--
          Texte à gauche
          <<--

          -><-
          Text centré
          -><-

      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

    %h3 Titraille

    .row.section
      - content = capture_haml do
        :plain
          # Titre 1
          ## Titre 2
          ### Titre 3
          #### Titre 4
          ##### Titre 5
          ###### Titre 6

      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

    %h3 Images

    .row.section
      - content = capture_haml do
        :plain
          ![Texte image non disponible](https://source.unsplash.com/random/348x100 "Légende au survol")
      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

    %h3 Icônes

    Seules les icônes de la section <a href='http://fontawesome.io/icons/#web-application'>web application</a> de FontAwesome sont disponibles dans le sélecteur, mais toutes les icônes peuvent être utilisées.

    .row.section
      - content = capture_haml do
        :plain
          %(globe)

      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

    %h3 Boutons

    .row.section
      - content = capture_haml do
        :plain
          (Texte du bouton=>http://www.google.fr/)
      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

    %h3 Listes

    .row.section
      - content = capture_haml do
        :plain
          - Item 1
          * Item 2
          + Item 3

          1. Item 1
          2. Item 2
          3. Item 3

      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

    %h3 Table

    .row.section
      - content = capture_haml do
        :plain
          Titre Colonne 1|Titre Colonne 2
          ---|---
          Cellule ligne 1, colonne 1|Cellule ligne 1, colonne 2
          Cellule ligne 2, colonne 1|Cellule ligne 2, colonne 2

      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

    %h3 Lettrines

    .row.section
      - content = capture_haml do
        :plain
          ^Ut^ wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio.

          ^^Ut^^ wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio.

          ^^^Ut^^^ wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio

          ^^^^Ut^^^^ wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio

      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

    %h3 Encarts

    .row.section
      - content = capture_haml do
        :plain
          Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio.

          %%%
          Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio.
          %%%

          Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio

          %%
          Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio
          %%

      .col-md-6.code<>= content.gsub(/^[ ]+/m, '')
      .col-md-6.preview
        .text-content= markdown(content)

app/views/shared/_messages.html.haml
.btn-group
  = link_to url_index, class: 'btn btn-default' do
    = 'actions.view_all'.t

  = link_to url_new, class: 'btn btn-success' do
    = icon_for(:create)
    %span.text= 'actions.create_new'.t

app/views/shared/_setting_field_templates.html.haml
.tpl#resource
  .resource-selector
    %input.form-control{type: :hidden, value:'{{= value}}', data: {name: '{{= setting }}'}}

    .form-group.has-feedback
      %label{for:'{{= id}}'} {{= label}}

      %select{id: '{{= id}}', style: 'width: 100%', required:'{{= setting_parameters.required ? \'required\' : \'no\'}}', placeholder: 'simple_form.placeholders.select'.t}
    -#     = options_for_select([['', '']] +  Page.custom_resources.keys.map {|c| [c.t, c.name]})
    -#
    -# - Page.custom_resources.each_pair do |cls, routes|
    -#   :ruby
    -#     collection = [['','']]
    -#     routes.each do |action|
    -#       action = action.to_s
    -#
    -#       case action
    -#       when 'instance'
    -#         cls.all.each do |m|
    -#           collection << [m.to_s, m.id]
    -#         end
    -#       else
    -#         collection << ["routes.#{action}".t, action]
    -#       end
    -#     end
    -#
    -#   .form-group.has-feedback.slave{class: cls.name.downcase, data: {master: '[name*="target_model"]'}}
    -#     = select_tag '', options_for_select(collection, resource.target_model), style: 'width: 100%', input_html: {required:'{{= setting_parameters.required ? \'required\' : \'no\'}}'}


= render 'shared/setting_field_templates_extra'

= render partial: 'direct_download'

app/views/shared/_sign_in.html.haml
.row.sign-in
  .col-md-6
    = simple_form_for(sign_in_model, url: session_path(:user), html: { role: 'form'}) do |f|
      %h3= 'actions.sign_in'.t
      = f.input :email, :autofocus => true
      = f.input :password

      = f.submit 'actions.connect'.t, class: 'btn btn-red btn-block'
      = link_to 'actions.recover_password'.t, new_password_path(resource)

  .col-md-6
    = simple_form_for(sign_up_model, url: registration_path(resource_name), html: { role: 'form'}) do |f|
      %h3= 'actions.sign_up'.t

      = f.input :email
      = f.input :password, as: :pwdcalc_simple
      = f.input :password_confirmation

      = f.submit 'actions.sign_up'.t, class: 'btn btn-grey btn-block'

= pwdcalc_hints

app/views/shared/_user_card.html.haml
= show_avatar user.avatar, :thumb

- if can? :edit, user
  = link_to user.name, [controller.controller_namespace, user].flatten
- else
  = user.name

= "(#{user.email})"
- if !user.user?
  .details
    - if user.role == 'admin'
      .label.label-warning= "roles.#{user.role}".t
    - else
      .label.label-info=  "roles.#{user.role}".t