config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", passwords: 'passwords', masquerades: 'admin/masquerades' }

  get '/result', to: 'static#s3_results', as: :s3_results

  resources :signed_urls, only: :index

  namespace :admin do
    root to: 'home#index'

    resources :users
    resources :seo_meta
  end

  resources :days do
    member do
      get :add_moments
    end
    resources :moments
  end

  get "/404", to: "errors#routing"
  post "/404", to: "errors#routing"
  put "/404", to: "errors#routing"
  patch "/404", to: "errors#routing"
  delete "/404", to: "errors#routing"
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  if Rails.env.dev?
    after_action :verify_authorized, :except => :index
    after_action :verify_policy_scoped, :only => :index
  end

  layout 'admin'

  before_filter :reject_unauthorized_user!

  load_and_authorize_resource

  def controller_namespace
    [:admin]
  end

  def is_admin?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ResourceExtensions
  include TraficExtensions
  include ResponseExtensions
  include DeviseExtensions
  include CustomsExtensions
  include ToggleExtensions
  include Pundit

  respond_to :html

  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :access_denied

  before_filter :masquerade_user!

  before_filter do
    # there MUST be a cleaner way :/
    if Rails.env.development?
      paths = Rails.application.paths['app/models'].to_a
      Rails.application.railties.each do |tie|
        next unless tie.respond_to? :paths
        paths += tie.paths['app/models'].to_a
      end

      paths.each do |path|
        next unless File.directory?(path)
        Dir.chdir path do
          Dir['**/*.rb'].each do |src|
            TPrint.debug "loading #{src[0..-4].classify}"
            src[0..-4].classify.constantize rescue nil
          end
        end
      end
    end
  end

  def is_admin?
    false
  end

  def controller_namespace
    []
  end

  def reject_unauthorized_user!
    unauthorized unless current_user.present? && current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_controller? name
    controller_name.to_s == name.to_s
  end

  def in_admin &block
    if controller.class.name =~ /^admin::/i
      if block_given?
        yield
      end
    end
  end
end

app/views/application/_direct_download.html.haml
- if CarrierWave::Uploader::Base.storage == CarrierWave::Storage::Fog
  %section.direct-upload-section
    %form{ action: "//#{ CarrierWave::Uploader::Base.fog_directory }.s3#{CarrierWave::Uploader::Base.fog_credentials[:region].present? ? "-" + CarrierWave::Uploader::Base.fog_credentials[:region] : ''}.amazonaws.com", method: 'post', enctype: 'multipart/form-data', class: 'direct-upload' }
      %input{ type: :hidden, name: :key }
      %input{ type: :hidden, name: 'AWSAccessKeyId', value: CarrierWave::Uploader::Base.fog_credentials[:aws_access_key_id] }
      %input{ type: :hidden, name: :acl, value: 'public-read' }
      %input{ type: :hidden, name: :policy }
      %input{ type: :hidden, name: :signature }
      %input{ type: :hidden, name: :success_action_status, value: "201" }
      %input{ type: :file, name: :file }

app/views/application/_edit.html.haml
.row
  .col-md-12
    = widget_box resource_class.t, icon_class_for(:edit), content_class: 'nopadding' do
      = render_partial_for_user 'form'

app/views/application/_form.html.haml
= simple_nested_form_for resource, url: controller.controller_namespace + [resource] do |f|
  %fieldset.inputs.panel-body
    = inputs_for resource, f
  %fieldset.inputs.panel-body
    = render_partial_for_user 'form_extra_fields', locals: local_assigns.merge(form: f)

  = default_actions

= render 'direct_download'

app/views/application/_index.html.haml
- if resource_class && resource_collection
  - resource_name = resource_class.model_name.human.underscore
  - resource_plural_name = resource_class.t
  - title_content = render_partial_for_user 'index_panel_header'

  .row
    .col-md-12
      = widget_box title_content, content_class: 'nopadding', before_title: collection_counter(resource_collection) do
        = contextual_partial 'index_before_collection'

        = collection resource_collection

        = contextual_partial 'index_after_collection'

app/views/application/_index_header.html.haml
- controller_breadcrumb

= contextual_partial 'collection_header_before_pills', locals: local_assigns

- in_admin do
  - if resource_class && can?(:create, resource_class) && controller.route_exists_for?(:new)
    - pill controller.resource_path(:new), class: 'btn-success' do
      = icon_for(:create)
      %span.text= 'actions.create'.t

= contextual_partial 'collection_header_after_pills', locals: local_assigns

- breadcrumb resource_class.t if resource_class

- content_for :pills do
  = pills
- content_for :breadcrumb do
  = breadcrumbs

- content_for :page_title do
  = resource_class ? resource_class.t : 'Boilerplate'

app/views/application/_list_item.html.haml
- if item.id.present?
  = contextual_partial 'list_item_before_details', locals: local_assigns
  = contextual_partial 'list_item_label', locals: local_assigns
  = contextual_partial 'list_item_after_details', locals: local_assigns
- else
  .item{class: item.class.name.underscore}
    %span.name= resource_label_for(item)

app/views/application/_list_item_actions.html.haml
- edit_url ||= controller.resource_path_for(item, :edit)
- destroy_url ||= controller.resource_path_for(item, :destroy)

= contextual_partial 'list_item_before_actions', locals: local_assigns

- if can? :edit, item
  = link_to edit_url, class: 'btn btn-default' do
    = icon_for(:edit)
    %span.text= 'admin.actions.edit'.t

- if can? :destroy, item
  = link_to destroy_url, method: :delete, class: 'btn btn-danger', data: {confirm: 'confirmations.destroy'.t} do
    = icon_for(:destroy)
    %span.text= 'admin.actions.destroy'.t

= contextual_partial 'list_item_after_actions', locals: local_assigns

app/views/application/_new_header.html.haml
- controller_breadcrumb
- breadcrumb resource_class.t, controller.resource_path(:index)
- breadcrumb 'admin.actions.create'.t

- content_for :pills do
  = pills

- content_for :breadcrumb do
  = breadcrumbs

- content_for :page_title do
  = resource_class.t

app/views/application/_show_boolean_field.html.haml
- if can? :view, resource, column
  %input{type: :checkbox, readonly: true, checked: value}
  %label= "#{controller.resource_name.singularize}.#{column}".tmf

app/views/application/_show_datetime_field.html.haml
- if can? :view, resource, column
  %strong= "#{controller.resource_name.singularize}.#{column}".tmfc
  - if value.present?
    = value.l
  - else
    Non définie

app/views/application/_show_image_field.html.haml
- if can? :view, resource, column
  - if value.class == PdfUploader
    %strong= "#{controller.resource_name.singularize}.#{column}".tmfc
    = link_to value.url do
      = icon 'file-pdf-o'
      = value
  - elsif value.respond_to?(:thumb)
    %strong= "#{controller.resource_name.singularize}.#{column}".tmf
    = image_tag(value.thumb)

app/views/application/_show_text_field.html.haml
- if can? :view, resource, column
  %strong= "#{controller.resource_name.singularize}.#{column}".tmfc
  .md-preview= value

app/views/application/new.html.haml
= render_partial_for_user 'new_header'
= render_partial_for_user 'new'

app/views/application/show.html.haml
= render_partial_for_user 'show_header'
= render_partial_for_user 'show'