config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", passwords: 'passwords', masquerades: 'admin/masquerades' }

  get '/result', to: 'static#s3_results', as: :s3_results

  resources :signed_urls, only: :index

  namespace :admin do
    root to: 'home#index'

    resources :users
    resources :seo_meta
  end

  resources :days do
    member do
      get :add_moments
    end
    resources :moments
  end

  get "/404", to: "errors#routing"
  post "/404", to: "errors#routing"
  put "/404", to: "errors#routing"
  patch "/404", to: "errors#routing"
  delete "/404", to: "errors#routing"
end

app/views/admin/shared/_dashboard.html.haml
- admin = (controller_name =~ /admin/ ? 'admin' : nil)
.row.dashboard
  - Dashboard.weighed_items.each do |klass, opts|
    :ruby
      unless_clause = opts[:unless]
      if unless_clause
        next if instance_exec(&unless_clause)
      end
      if_clause = opts[:if]
      if if_clause
        next unless instance_exec(&if_clause)
      end
      size = opts[:size] || 1

      if opts[:scope].present?
        scope = opts[:scope]
        scope = scope.is_a?(Array) ? klass.send(scope[0], instance_exec(&scope[1])) : klass.send(scope)
      else
        scope = klass
      end

      scope = opts[:order].present? ? scope.order(opts[:order]) : scope.order('created_at DESC')
      scope = opts[:limit].present? ? scope.limit(opts[:limit]) : scope.limit(5)

    %div{class: "col-md-#{size*6}"}
      - title_content = opts[:title] || "models.dashboard.#{klass.name.pluralize.underscore}".t(default: render_partial_for_user('index_panel_header', locals: {resource_class: klass}))

      - title = capture_haml do
        = icon_for(klass)
        = title_content

      - if opts[:columns].present?
        :ruby
          url = [:admin, klass]

          def get_proc(c, *args)
            try(:"admin_resource_#{c}_proc", *args) ||
            try(:"resource_#{c}_proc", *args) ||
            try(:"#{c}_proc", *args) ||
            try(c, *args)
          end

          options = {
            columns: opts[:columns].map { |c|
              if c.is_a?(Hash)
                c.map do |k,v|
                  get_proc(k, *v)
                end
              else
                get_proc(c)
              end
            }.flatten.compact,
          }.reverse_merge(opts)

        .panel.panel-default{class: size == 1 && 'short-actions'}
          .panel-heading
            = collection_counter(scope)
            = icon_for(klass)
            %h5.panel-title
              = link_to url do
                = title_content

          = models_list scope, options

          - if can?(:create, klass) && (new_url = url_for([:new, :admin, klass.name.underscore.downcase].compact) rescue nil)
            .panel-footer
              = link_to new_url, class: 'btn btn-success' do
                = icon_for(:create)
                %span.text= 'admin.actions.add'.t

      - else
        = widget_box title, class: "panel-default #{size == 1 && 'short-actions'}", before_title: collection_counter(klass.where(nil)) do
          = collection scope, resource_class: klass, no_pagination: true
          - if can?(:create, klass) && (new_url = url_for([:new, :admin, klass.name.underscore.downcase].compact) rescue nil)
            .panel-footer
              = link_to new_url, class: 'btn btn-success' do
                = icon_for(:create)
                %span.text= 'admin.actions.add'.t

app/views/admin/shared/_nav.html.haml
= nav_link_to admin_root_path, 'nav.admin.dashboard'.t, :home, icon_class_for(:dashboard)
= nav_link_to admin_root_path, 'nav.admin.root'.t, :home, icon_class_for(:main_nav) do
  = nav_link_to User

app/views/admin/shared/_session.html.haml
- if user_signed_in?
  %span.welcome.pull-right
    .pull-right{class: 'dropdown-toggle', data: { toggle: 'dropdown' }}
      = show_avatar current_user.avatar, :thumb
      = icon('chevron-down')

    %ul.dropdown-menu
      %li
        = link_to admin_user_path(current_user) do
          = icon_for(User)
          %span.text= 'actions.show_profile'.t

      %li
        = link_to edit_admin_user_path(current_user) do
          = icon_for(:profile)
          %span.text= 'actions.edit_profile'.t

      - if user_masquerade?
        %li
          = link_to back_user_masquerade_index_path do
            = icon_for(:sign_out)
            %span.text= 'reverse_masquerade'.t

      - else
        %li
          = link_to destroy_user_session_path, method: :delete do
            = icon_for(:sign_out)
            %span.text= 'actions.sign_out'.t

    .session
      - if user_masquerade?
        %span.text.masqueraded!= 'masqueraded'.t user: current_user.name
      - else
        = link_to admin_user_path(current_user) do
          %span.text= current_user.name

      .details
        - if current_user.admin?
          .label.label-warning= "roles.#{current_user.role}".t
        - else
          .label.label-info= "roles.#{current_user.role}".t